# Generated by Django 4.2.5 on 2023-10-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
