# Generated by Django 4.2.5 on 2023-10-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='index',
        ),
    ]
