# Generated by Django 4.2.5 on 2023-11-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_product_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
    ]
